substitutions:
  device_name: airco-ctrl
  friendly_name: Airco Controller

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2026.3.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: INFO
  baud_rate: 0

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

external_components:
  - source: github://Astute4185/MHI-AC-Ctrl-ESPHome_ESP-IDF@master
    components: [MhiAcCtrl]

MhiAcCtrl:
  # Set to 20 if your unit does not support 33-byte frames.
  frame_size: 20
  sck_pin: 21
  miso_pin: 34
  mosi_pin: 48

climate:
  - platform: MhiAcCtrl
    name: "${friendly_name}"

select:
  - platform: MhiAcCtrl
    vertical_vanes:
      name: "Vanes Up-Down"
    horizontal_vanes:
      name: "Vanes Left-Right"

switch:
  - platform: MhiAcCtrl
    vanes_3d_auto:
      name: "3D Auto"

sensor:
  - platform: MhiAcCtrl
    outdoor_temperature:
      name: "Outdoor Temperature"
