#!/usr/bin/env bash
set -euo pipefail

# Clean ESPHome/PlatformIO build artifacts generated by component compile tests.
# Default mode removes generated build output only.
# Use --all to remove the full test .esphome directory, including validated config cache.

usage() {
  cat <<'USAGE'
Usage: scripts/clean-test-builds.sh [--all] [--dry-run]

Options:
  --all      Remove the full test .esphome directory, not just .esphome/build.
             This also clears ESPHome validated config cache for test YAMLs.
  --dry-run  Print what would be removed without deleting anything.
  -h, --help Show this help.
USAGE
}

REMOVE_ALL=0
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --all)
      REMOVE_ALL=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TEST_COMPONENT_DIR="$REPO_ROOT/tests/components/MhiAcCtrl"

if [[ ! -d "$TEST_COMPONENT_DIR" ]]; then
  echo "Expected test component directory not found: $TEST_COMPONENT_DIR" >&2
  exit 1
fi

remove_path() {
  local path="$1"

  if [[ ! -e "$path" ]]; then
    echo "skip: $path"
    return
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "would remove: $path"
    return
  fi

  echo "remove: $path"
  rm -rf -- "$path"
}

if [[ "$REMOVE_ALL" -eq 1 ]]; then
  remove_path "$TEST_COMPONENT_DIR/.esphome"
else
  remove_path "$TEST_COMPONENT_DIR/.esphome/build"
  remove_path "$TEST_COMPONENT_DIR/.esphome/platformio"
fi

# Clean local unit-test build scratch directories if present.
remove_path "$REPO_ROOT/.test-build"
remove_path "$TEST_COMPONENT_DIR/.test-build"

echo "clean-test-builds complete"
